import { gzipSync } from "node:zlib";
import { fileURLToPath } from "node:url";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import postcss from "postcss";
import tailwindcss from "@tailwindcss/postcss";
import { container, gridMin } from "../tokens/layout.ts";
import { spacing } from "../tokens/spacing.ts";
import { elementDefaults, leading, text, tracking, weight } from "../tokens/typography.ts";

const generatedHeader = "// Code generated by pnpm tokens. DO NOT EDIT.";
const generatedCssHeader = "/* Code generated by pnpm tokens. DO NOT EDIT. */";
const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const webRoot = join(scriptDirectory, "..");
const generatedDirectory = join(webRoot, "tokens", "generated");
// Generator config, not a token scale — these emit no CSS custom property. Names only, in
// ascending order; Tailwind's own --breakpoint-* defaults carry the widths, and restating them
// here would be a second, unread definition free to drift. Listing the names explicitly rather
// than reading them from Tailwind keeps the exposed tier set a deliberate choice: a breakpoint
// Tailwind adds later cannot silently widen every responsive class map against the size budget.
// assertBreakpointsMatchTailwind verifies these names and their order against Tailwind.
const breakpointNames = ["sm", "md", "lg", "xl", "2xl"];
const spacingSteps = [0, ...Object.keys(spacing).map(Number)];
const textSteps = Object.keys(text).map(Number);
const weightSteps = Object.keys(weight).map(Number);
const columns = Array.from({ length: 12 }, (_, index) => index + 1);
const rowSpans = Array.from({ length: 6 }, (_, index) => index + 1);
// Its own range, deliberately not rowSpans: grid spans and line clamps are unrelated prop
// contracts that only coincide at 1-6, so raising one ceiling must not move the other.
const lineClamps = Array.from({ length: 6 }, (_, index) => index + 1);
const generatedThemeImport = '@import "../tokens/generated/theme.css";';

const deliberateOverrides = new Set([
  ...Object.keys(spacing).map((step) => `--spacing-${step}`),
  "--leading-tight",
  "--leading-snug",
  "--leading-normal",
  "--leading-relaxed",
  "--tracking-tight",
  "--tracking-normal",
  "--tracking-wide",
  "--tracking-wider",
]);

function values<T>(record: Record<string, T>) {
  return Object.keys(record);
}

function quote(value: string | number | boolean) {
  return JSON.stringify(value);
}

function union(items: Array<string | number | boolean>) {
  return items.map(quote).join(" | ");
}

function record(entries: Array<[string | number | boolean, string]>, indent = "  ") {
  return entries.map(([key, value]) => `${indent}${quote(String(key))}: ${quote(value)},`).join("\n");
}

function flatMap(name: string, type: string, entries: Array<[string | number | boolean, string]>) {
  return `export const ${name}: BaseClassMap<${type}> = {\n${record(entries)}\n};`;
}

function responsiveMap(name: string, type: string, entries: Array<[string | number | boolean, string]>) {
  // An empty class stays empty at every tier. Prefixing it would emit a bare "md:", which is
  // truthy enough to survive the primitives' filter and land in the DOM as a junk class.
  const tier = (prefix: string) => record(entries.map(([key, className]) => [key, prefix && className ? `${prefix}:${className}` : className]), "    ");
  return `export const ${name}: ResponsiveClassMap<${type}> = {\n  base: {\n${tier("")}\n  },\n${breakpointNames
    .map((breakpoint) => `  ${quote(breakpoint)}: {\n${tier(breakpoint)}\n  },`)
    .join("\n")}\n};`;
}

function classEntries(items: Array<string | number | boolean>, className: (item: string | number | boolean) => string) {
  return items.map((item) => [item, className(item)] as [string | number | boolean, string]);
}

function buildTheme() {
  const lines = [generatedCssHeader, "", "@theme {"];

  for (const [step, value] of Object.entries(spacing)) {
    lines.push(`  --spacing-${step}: ${value};`);
  }
  for (const [step, value] of Object.entries(text)) {
    lines.push(`  --text-${step}: ${value.size};`);
    lines.push(`  --text-${step}--line-height: ${value.lineHeight};`);
  }
  for (const [step, value] of Object.entries(weight)) {
    lines.push(`  --font-weight-${step}: ${value};`);
  }
  for (const [name, value] of Object.entries(leading)) {
    lines.push(`  --leading-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(tracking)) {
    lines.push(`  --tracking-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(container)) {
    lines.push(`  --container-${name}: ${value};`);
  }
  lines.push("}", "");
  for (const [name, value] of Object.entries(gridMin)) {
    lines.push(`@utility grid-auto-${name} {`, `  grid-template-columns: repeat(auto-fit, minmax(${value}, 1fr));`, "}", "");
  }
  return lines.join("\n");
}

function buildTypes() {
  return `${generatedHeader}

export type Breakpoint = ${union(breakpointNames)};
export const responsiveTiers = ["base", ${breakpointNames.map(quote).join(", ")}] as const;
export type Spacing = ${union(spacingSteps)};
export type TextSize = ${union(textSteps)};
export type Weight = ${union(weightSteps)};
export type Leading = ${union(values(leading))};
export type Tracking = ${union(values(tracking))};
export type Background = ${union(["none", "background", "card", "popover", "primary", "secondary", "muted", "accent", "destructive"])};
export type Radius = ${union(["none", "sm", "md", "lg", "xl", "2xl", "3xl", "4xl", "full"])};
export type Border = ${union(["none", "all", "top", "right", "bottom", "left", "x", "y"])};
export type Shadow = ${union(["none", "sm", "md", "lg", "xl"])};
export type Overflow = ${union(["visible", "hidden", "clip", "auto", "x-auto", "y-auto"])};
export type Width = ${union(["auto", "full", "fit", "min", "max"])};
export type Height = ${union(["auto", "full", "screen", "svh", "dvh"])};
export type MinHeight = ${union(["none", "full", "screen", "svh", "dvh"])};
export type Direction = ${union(["row", "row-reverse", "col", "col-reverse"])};
export type StackAlign = ${union(["start", "center", "end", "stretch", "baseline"])};
export type Justify = ${union(["start", "center", "end", "between", "around", "evenly"])};
export type StackWrap = ${union(["nowrap", "wrap", "wrap-reverse"])};
export type TextAlign = ${union(["start", "center", "end"])};
export type TextWrap = ${union(["normal", "balance", "pretty", "nowrap"])};
export type Color = ${union(["default", "muted", "primary", "accent", "destructive", "inverse"])};
export type Family = ${union(["sans", "mono"])};
export type Transform = ${union(["none", "uppercase", "lowercase", "capitalize"])};
export type Truncate = ${union([true, false])};
export type LineClamp = ${union(lineClamps)};
export type Columns = ${union(columns)};
export type ColSpan = Columns | "full";
export type RowSpan = ${union(rowSpans)} | "full";
export type MinItemWidth = ${union(values(gridMin))};
export type MaxWidth = ${union([...values(container), "full"])};
export type LayoutElement = ${union(["div", "section", "article", "header", "footer", "main", "aside", "nav", "figure", "ul", "li"])};
export type TextElement = ${union(Object.keys(elementDefaults))};
export type ElementDefault = { size?: TextSize; weight?: Weight };
export type ClassMapKey<Value> = Value extends boolean ? \`${"${Value}"}\` : Value extends PropertyKey ? Value : never;
export type BaseClassMap<Value> = Record<ClassMapKey<Value>, string>;
export type ResponsiveClassMap<Value extends PropertyKey> = Record<"base" | Breakpoint, Record<Value, string>>;
`;
}

function buildClassMaps() {
  const spacingMap = (name: string, prefix: string, responsive: boolean, allowAuto = false) => {
    const entries = classEntries(allowAuto ? [...spacingSteps, "auto"] : spacingSteps, (step) => `${prefix}-${step}`);
    return responsive ? responsiveMap(`${name}Map`, allowAuto ? "Spacing | \"auto\"" : "Spacing", entries) : flatMap(`${name}Map`, "Spacing", entries);
  };
  const maps = [
    spacingMap("p", "p", true),
    spacingMap("px", "px", true),
    spacingMap("py", "py", true),
    spacingMap("pt", "pt", false),
    spacingMap("pr", "pr", false),
    spacingMap("pb", "pb", false),
    spacingMap("pl", "pl", false),
    spacingMap("m", "m", true),
    spacingMap("mx", "mx", true, true),
    spacingMap("my", "my", true),
    spacingMap("mt", "mt", false),
    spacingMap("mr", "mr", false),
    spacingMap("mb", "mb", false),
    spacingMap("ml", "ml", false),
    spacingMap("gap", "gap", true),
    spacingMap("gapX", "gap-x", true),
    spacingMap("gapY", "gap-y", true),
    responsiveMap("sizeMap", "TextSize", classEntries(textSteps, (step) => `text-${step}`)),
    flatMap("weightMap", "Weight", classEntries(weightSteps, (step) => `font-${step}`)),
    flatMap("leadingMap", "Leading", classEntries(values(leading), (name) => `leading-${name}`)),
    flatMap("trackingMap", "Tracking", classEntries(values(tracking), (name) => `tracking-${name}`)),
    flatMap("colorMap", "Color", [["default", "text-foreground"], ["muted", "text-muted-foreground"], ["primary", "text-primary"], ["accent", "text-accent-foreground"], ["destructive", "text-destructive"], ["inverse", "text-primary-foreground"]]),
    flatMap("familyMap", "Family", classEntries(["sans", "mono"], (name) => `font-${name}`)),
    flatMap("textAlignMap", "TextAlign", classEntries(["start", "center", "end"], (name) => `text-${name}`)),
    flatMap("transformMap", "Transform", [["none", "normal-case"], ["uppercase", "uppercase"], ["lowercase", "lowercase"], ["capitalize", "capitalize"]]),
    flatMap("truncateMap", "Truncate", [[true, "truncate"], [false, ""]]),
    flatMap("lineClampMap", "LineClamp", classEntries(lineClamps, (step) => `line-clamp-${step}`)),
    flatMap("textWrapMap", "TextWrap", [["normal", "text-wrap"], ["balance", "text-balance"], ["pretty", "text-pretty"], ["nowrap", "text-nowrap"]]),
    flatMap("bgMap", "Background", [["none", ""], ["background", "bg-background"], ["card", "bg-card"], ["popover", "bg-popover"], ["primary", "bg-primary"], ["secondary", "bg-secondary"], ["muted", "bg-muted"], ["accent", "bg-accent"], ["destructive", "bg-destructive"]]),
    flatMap("radiusMap", "Radius", classEntries(["none", "sm", "md", "lg", "xl", "2xl", "3xl", "4xl", "full"], (name) => `rounded-${name}`)),
    flatMap("borderMap", "Border", [["none", ""], ["all", "border"], ["top", "border-t"], ["right", "border-r"], ["bottom", "border-b"], ["left", "border-l"], ["x", "border-x"], ["y", "border-y"]]),
    flatMap("shadowMap", "Shadow", classEntries(["none", "sm", "md", "lg", "xl"], (name) => `shadow-${name}`)),
    flatMap("overflowMap", "Overflow", classEntries(["visible", "hidden", "clip", "auto", "x-auto", "y-auto"], (name) => `overflow-${name}`)),
    responsiveMap("widthMap", "Width", classEntries(["auto", "full", "fit", "min", "max"], (name) => `w-${name}`)),
    responsiveMap("heightMap", "Height", classEntries(["auto", "full", "screen", "svh", "dvh"], (name) => `h-${name}`)),
    // `none` maps to min-h-auto, not an empty class. `auto` is CSS's initial
    // value, so the base tier behaves as before, but an empty string cannot
    // reset a min-height inherited from a lower breakpoint.
    responsiveMap("minHeightMap", "MinHeight", [["none", "min-h-auto"], ["full", "min-h-full"], ["screen", "min-h-screen"], ["svh", "min-h-svh"], ["dvh", "min-h-dvh"]]),
    responsiveMap("directionMap", "Direction", classEntries(["row", "row-reverse", "col", "col-reverse"], (name) => `flex-${name}`)),
    responsiveMap("stackAlignMap", "StackAlign", classEntries(["start", "center", "end", "stretch", "baseline"], (name) => `items-${name}`)),
    responsiveMap("justifyMap", "Justify", classEntries(["start", "center", "end", "between", "around", "evenly"], (name) => `justify-${name}`)),
    flatMap("stackWrapMap", "StackWrap", classEntries(["nowrap", "wrap", "wrap-reverse"], (name) => `flex-${name}`)),
    responsiveMap("columnsMap", "Columns", classEntries(columns, (value) => `grid-cols-${value}`)),
    responsiveMap("colSpanMap", "ColSpan", classEntries([...columns, "full"], (value) => `col-span-${value}`)),
    responsiveMap("rowSpanMap", "RowSpan", classEntries([...rowSpans, "full"], (value) => `row-span-${value}`)),
    flatMap("minItemWidthMap", "MinItemWidth", classEntries(values(gridMin), (name) => `grid-auto-${name}`)),
    responsiveMap("maxWidthMap", "MaxWidth", classEntries([...values(container), "full"], (name) => `max-w-${name}`)),
  ];
  const defaults = Object.entries(elementDefaults)
    .map(([element, defaults]) => `  ${quote(element)}: ${JSON.stringify(defaults)},`)
    .join("\n");
  return `${generatedHeader}\n\nimport type {\n  Background,\n  BaseClassMap,\n  Border,\n  ColSpan,\n  Color,\n  Columns,\n  Direction,\n  ElementDefault,\n  Family,\n  Height,\n  Justify,\n  Leading,\n  LineClamp,\n  MaxWidth,\n  MinHeight,\n  MinItemWidth,\n  Overflow,\n  Radius,\n  ResponsiveClassMap,\n  RowSpan,\n  Shadow,\n  Spacing,\n  StackAlign,\n  StackWrap,\n  TextAlign,\n  TextElement,\n  TextSize,\n  TextWrap,\n  Tracking,\n  Transform,\n  Truncate,\n  Weight,\n  Width,\n} from "./types.ts";\n\n${maps.join("\n\n")}\n\nexport const elementDefaults: Record<TextElement, ElementDefault> = {\n${defaults}\n};\n`;
}

function readDefaultTheme() {
  return readFileSync(fileURLToPath(import.meta.resolve("tailwindcss/theme.css")), "utf8");
}

function assertBreakpointsMatchTailwind(defaultTheme: string) {
  const defaults = [...defaultTheme.matchAll(/--breakpoint-([a-z0-9-]+)\s*:/g)].map((match) => match[1]);
  const missing = breakpointNames.filter((name) => !defaults.includes(name));
  if (missing.length > 0) {
    throw new Error(`Breakpoint names are not defined by Tailwind's default theme: ${missing.join(", ")}`);
  }
  // resolveResponsive walks the tiers in emitted order, so the order must be Tailwind's own
  // ascending order. Reading it back from the default theme is what keeps that verifiable.
  const ordered = defaults.filter((name) => breakpointNames.includes(name));
  if (ordered.join(" ") !== breakpointNames.join(" ")) {
    throw new Error(`Breakpoint order drifted from Tailwind's default theme: expected ${ordered.join(", ")}`);
  }
}

function assertNoUnexpectedCollisions(theme: string, defaultTheme: string) {
  const defaultNames = new Set([...defaultTheme.matchAll(/(--[a-z0-9-]+)\s*:/g)].map((match) => match[1]));
  const emittedNames = [...theme.matchAll(/(--[a-z0-9-]+)\s*:/g)].map((match) => match[1]);
  const collisions = emittedNames.filter((name) => defaultNames.has(name) && !deliberateOverrides.has(name));
  if (collisions.length > 0) {
    throw new Error(`Token names collide with Tailwind defaults: ${collisions.join(", ")}`);
  }
  // Tailwind's deprecated --max-width-* scale wins over --container-*, so a container token
  // whose name it already defines is emitted and then silently ignored. `prose` is the one.
  const shadowed = emittedNames.filter(
    (name) => name.startsWith("--container-") && defaultNames.has(name.replace("--container-", "--max-width-")),
  );
  if (shadowed.length > 0) {
    throw new Error(`Container tokens are shadowed by Tailwind's --max-width-* scale: ${shadowed.join(", ")}`);
  }
}

function escapeClassSelector(className: string) {
  return className.replace(/^[0-9]/, (digit) => `\\3${digit} `).replace(/[.:\/]/g, (character) => `\\${character}`);
}

async function runProbe(theme: string, classMaps: string) {
  const emittedClasses = [...new Set([...classMaps.matchAll(/: "([^"]+)"/g)].map((match) => match[1]))];
  const globals = readFileSync(join(webRoot, "app", "globals.css"), "utf8");
  if (!globals.includes(generatedThemeImport)) {
    throw new Error(`app/globals.css must import the generated theme as ${generatedThemeImport}`);
  }
  // Probe the app's own stylesheet with the fresh theme swapped in for the on-disk copy. The
  // class maps name shadcn's semantic color utilities, which resolve only alongside globals.css.
  const stylesheet = globals.replace(generatedThemeImport, theme);
  const input = `${stylesheet}\n@source inline("${[...emittedClasses, "p-4", "p-2.5", "h-8", "size-6"].join(" ")}");`;
  const result = await postcss([tailwindcss({ base: webRoot })]).process(input, {
    from: join(webRoot, "app", "probe.css"),
  });

  const selectors = new Set<string>();
  result.root.walkRules((rule) => {
    for (const selector of rule.selector.split(",")) selectors.add(selector.trim());
  });
  const unbuilt = emittedClasses.filter((className) => !selectors.has(`.${escapeClassSelector(className)}`));
  if (unbuilt.length > 0) {
    throw new Error(`Tailwind probe failed: emitted classes produced no CSS rule: ${unbuilt.join(", ")}`);
  }

  const css = result.css.replace(/\s+/g, "");
  const emittedNames = [...theme.matchAll(/(--[a-z0-9-]+)\s*:/g)].map((match) => match[1]);
  for (const name of emittedNames) {
    if (!css.includes(`${name}:`)) {
      throw new Error(`Tailwind probe failed: ${name} did not resolve to an emitted token`);
    }
  }
  const expected = [
    ["p-4", "padding:calc(var(--spacing)*4)"],
    ["p-2.5", "padding:calc(var(--spacing)*2.5)"],
    ["h-8", "height:calc(var(--spacing)*8)"],
    ["size-6", "width:calc(var(--spacing)*6)", "height:calc(var(--spacing)*6)"],
  ];
  for (const [utility, ...declarations] of expected) {
    const selector = `.${utility.replace(".", "\\.")}{`;
    const start = css.indexOf(selector);
    const rule = start === -1 ? "" : css.slice(start, css.indexOf("}", start));
    if (!declarations.every((declaration) => rule.includes(declaration))) {
      throw new Error(`Tailwind probe failed: ${utility} no longer computes against --spacing`);
    }
  }
}

async function main() {
  const artifacts = new Map([
    [join(generatedDirectory, "theme.css"), buildTheme()],
    [join(generatedDirectory, "types.ts"), buildTypes()],
    [join(generatedDirectory, "class-maps.ts"), buildClassMaps()],
  ]);
  const theme = artifacts.get(join(generatedDirectory, "theme.css"));
  const classMaps = artifacts.get(join(generatedDirectory, "class-maps.ts"));
  if (!theme || !classMaps) throw new Error("Token artifacts were not generated");

  const defaultTheme = readDefaultTheme();
  assertBreakpointsMatchTailwind(defaultTheme);
  assertNoUnexpectedCollisions(theme, defaultTheme);
  await runProbe(theme, classMaps);

  const gzipBytes = gzipSync(classMaps).byteLength;
  console.log(`class-maps.ts gzip: ${gzipBytes} bytes`);
  if (gzipBytes > 12 * 1024) throw new Error("class-maps.ts exceeds the 12 KB gzip budget");

  const check = process.argv.includes("--check");
  let stale = false;
  for (const [path, contents] of artifacts) {
    const existing = (() => {
      try {
        return readFileSync(path, "utf8");
      } catch {
        return undefined;
      }
    })();
    if (existing !== contents) {
      stale = true;
      if (!check) {
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, contents);
      }
    }
  }
  if (check && stale) {
    throw new Error("Generated token artifacts are stale. Run pnpm tokens.");
  }
}

await main();
