// Emits app/theme.css from tokens.mjs. Run with `pnpm theme:build`.
//
// The whole file is generated, header and tail included, so regenerating is
// idempotent and cannot half-replace a block. Never hand-edit app/theme.css.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { T, SERIES_LIGHT, SERIES_DARK, RAMP } from "./tokens.mjs";
import { fitGamut } from "./oklch.mjs";

const GROUPS = [
  ["Surface — where content sits", ["surface-page","surface-raised","surface-sunken","surface-overlay","surface-row-hover","surface-row-focus","surface-row-selected"]],
  ["Content — ink", ["content-primary","content-secondary","content-muted","content-disabled","content-inverse","content-link"]],
  ["Edge — boundaries and the focus ring", ["edge-hairline","edge","edge-strong","focus"]],
  ["Accent — achromatic by design; colour is reserved for data", ["accent-solid","accent-hover","accent-active","accent-subtle","on-solid"]],
  ["Status — state of a thing the system did", ["success-solid","success-subtle","success-edge","success-ink","warning-solid","warning-subtle","warning-edge","warning-ink","danger-solid","danger-subtle","danger-edge","danger-ink","info-solid","info-subtle","info-edge","info-ink"]],
  ["Trend — direction of a measure. Never status.", ["trend-up-solid","trend-up-subtle","trend-up-edge","trend-up-ink","trend-down-solid","trend-down-subtle","trend-down-edge","trend-down-ink","trend-flat-solid","trend-flat-subtle","trend-flat-edge","trend-flat-ink"]],
  ["Freshness — how old the system's knowledge is", ["fresh-ink","fresh-subtle","fresh-edge","aging-ink","aging-subtle","aging-edge","stale-ink","stale-subtle","stale-edge","unavailable-ink","unavailable-subtle","unavailable-edge"]],
  ["Provenance — observed vs. derived", ["observed","derived","derived-subtle"]],
  ["Diverging ramp — signed change against a baseline", ["delta-down-3","delta-down-2","delta-down-1","delta-mid","delta-up-1","delta-up-2","delta-up-3"]],
];

const fmt = ([L, C, H]) => `oklch(${L} ${C} ${C === 0 ? 0 : H})`;

function block(mode) {
  const out = [];
  for (const [title, names] of GROUPS) {
    out.push(`\n  /* ${title} */`);
    const width = Math.max(...names.map((n) => n.length));
    for (const n of names) out.push(`  --${n}:${" ".repeat(width - n.length + 1)}${fmt(fitGamut(...T[n][mode]))};`);
  }
  out.push("\n  /* Categorical series — identity only. Slots 7-8 hold the trend hues,\n     so a chart with six or fewer series never borrows a trend colour. */");
  (mode === "l" ? SERIES_LIGHT : SERIES_DARK).forEach((h, i) => out.push(`  --series-${i + 1}:     ${h};`));
  out.push(`  --series-other: ${fmt(fitGamut(...T["series-other"][mode]))};`);
  out.push("\n  /* Sequential ramp — magnitude. ramp-1 recedes toward the surface. */");
  (mode === "l" ? RAMP : [...RAMP].reverse()).forEach((h, i) => out.push(`  --ramp-${i + 1}:       ${h};`));
  return out.join("\n");
}

const themeNames = [
  ...GROUPS.flatMap(([, names]) => names),
  ...SERIES_LIGHT.map((_, i) => `series-${i + 1}`), "series-other",
  ...RAMP.map((_, i) => `ramp-${i + 1}`),
];

const HEADER = `/* Market Scout semantic colour tokens.
 *
 * GENERATED by scripts/theme/generate.mjs from scripts/theme/tokens.mjs.
 * Do not hand-edit: the families are calibrated against each other, and a
 * single tuned-by-eye value breaks that silently — nothing in the Next build
 * checks contrast. Edit tokens.mjs, then \`pnpm theme:build && pnpm theme:check\`.
 *
 * Two layers, same as the rest of the styling system:
 *   :root / .dark   raw values, authored in OKLCH, fitted to sRGB
 *   @theme inline   Tailwind utilities over those values
 *
 * \`inline\` is load-bearing: it makes \`bg-surface-raised\` emit
 * \`var(--surface-raised)\` rather than a copy of the light value, so the .dark
 * block actually overrides it.
 *
 * Two invariants hold across the whole set and are what make it safe to compose:
 *
 *   1. \`on-solid\` is legible on EVERY \`*-solid\` fill (>= 4.5:1). Light-mode
 *      solids therefore stay at or below OKLCH L 0.52; dark-mode solids at or
 *      above L 0.68. A new solid outside that band breaks the invariant.
 *   2. Every \`*-ink\` clears 4.5:1 on its own \`*-subtle\` background AND on
 *      \`surface-raised\`, so a badge and a bare inline label use the same ink.
 *
 * See agent-context/lib/web-guide.md § Colour for the families and when to
 * reach for each one.
 */
`;

const TAIL = `
/* Sidebar keeps its own shadcn namespace — \`components/ui/sidebar.tsx\` reads
 * these names directly. They are aliases, never independent values, so the
 * sidebar cannot drift from the palette above. */
:root, .dark {
  --sidebar:                    var(--surface-sunken);
  --sidebar-foreground:         var(--content-primary);
  --sidebar-primary:            var(--accent-solid);
  --sidebar-primary-foreground: var(--on-solid);
  --sidebar-accent:             var(--surface-row-hover);
  --sidebar-accent-foreground:  var(--content-primary);
  --sidebar-border:             var(--edge);
  --sidebar-ring:               var(--focus);
}

@theme inline {
  --color-sidebar:                    var(--sidebar);
  --color-sidebar-foreground:         var(--sidebar-foreground);
  --color-sidebar-primary:            var(--sidebar-primary);
  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --color-sidebar-accent:             var(--sidebar-accent);
  --color-sidebar-accent-foreground:  var(--sidebar-accent-foreground);
  --color-sidebar-border:             var(--sidebar-border);
  --color-sidebar-ring:               var(--sidebar-ring);
}

/* Pattern is the second provenance channel. Hue alone cannot carry "this value
 * was inferred, not observed" — it has to survive greyscale, printing, and
 * forced-colors. Geometry is exposed as vars so an SVG <pattern> in a chart can
 * match the DOM utility exactly. */
:root {
  --hatch-angle: 45deg;
  --hatch-gap: 7px;
  --hatch-line: 1px;
  /* Faded so a label stays readable through the fill. The ink beside it —
     \`text-derived\`, \`text-unavailable-ink\` — is the primary signal. */
  --hatch-derived: color-mix(in oklch, var(--derived) 30%, transparent);
  --hatch-unavailable-ink: color-mix(in oklch, var(--unavailable-ink) 30%, transparent);
}

@utility hatch-derived {
  background-image: repeating-linear-gradient(
    var(--hatch-angle),
    var(--hatch-derived) 0,
    var(--hatch-derived) var(--hatch-line),
    transparent var(--hatch-line),
    transparent var(--hatch-gap)
  );
}

@utility hatch-unavailable {
  background-image: repeating-linear-gradient(
    var(--hatch-angle),
    var(--hatch-unavailable-ink) 0,
    var(--hatch-unavailable-ink) var(--hatch-line),
    transparent var(--hatch-line),
    transparent var(--hatch-gap)
  );
}
`;

const css = [
  HEADER,
  `:root {${block("l")}\n}`,
  "",
  `.dark {${block("d")}\n}`,
  "",
  `@theme inline {\n${themeNames.map((n) => `  --color-${n}: var(--${n});`).join("\n")}\n}`,
  TAIL,
].join("\n");

const out = fileURLToPath(new URL("../../app/theme.css", import.meta.url));

// `--check` guards the other half of the staleness problem: tokens.mjs edited,
// theme.css never regenerated. The checks would pass against the new spec while
// the browser still renders the old CSS.
if (process.argv.includes("--check")) {
  const onDisk = readFileSync(out, "utf8");
  if (onDisk !== css) {
    console.error("app/theme.css is stale — tokens.mjs has changed. Run `pnpm theme:build`.");
    process.exit(1);
  }
  console.log("app/theme.css matches tokens.mjs");
} else {
  writeFileSync(out, css);
  console.log(`wrote ${out}`);
}
