// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classify.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/lib/pq"
)

const listCrossTableSlugs = `-- name: ListCrossTableSlugs :many
SELECT slug FROM (
    SELECT slug FROM canonical_roles
    UNION ALL SELECT slug FROM specializations
    UNION ALL SELECT slug FROM skills
    UNION ALL SELECT slug FROM role_dimensions
) t
GROUP BY slug
HAVING count(*) > 1
ORDER BY slug
`

// Slugs that live in more than one taxonomy table. mcp.save_enrichment rejects
// any payload naming one (slug_collision), even as reuse, so cmd/classify
// offers none of them.
func (q *Queries) ListCrossTableSlugs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCrossTableSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNearDuplicatePairs = `-- name: ListNearDuplicatePairs :many
SELECT a.ord::int AS left_index, b.ord::int AS right_index
FROM jsonb_array_elements($1::jsonb) WITH ORDINALITY AS a(term, ord)
JOIN jsonb_array_elements($1::jsonb) WITH ORDINALITY AS b(term, ord)
  ON b.ord > a.ord
WHERE greatest(
          public.similarity(a.term ->> 'slug', b.term ->> 'slug'),
          public.similarity(a.term ->> 'name', b.term ->> 'name'))::numeric
      >= $2::numeric
ORDER BY a.ord, b.ord
`

type ListNearDuplicatePairsParams struct {
	Terms     json.RawMessage
	Threshold string
}

type ListNearDuplicatePairsRow struct {
	LeftIndex  int32
	RightIndex int32
}

// Pairs among the given terms that mcp.save_enrichment's within-payload dedup
// (Phase C, 000043) would treat as one concept: the greater of slug and name
// similarity at or above its c_payload_dup_at. cmd/classify drops the less
// probable side of each pair before saving, so the save has nothing to drop.
// terms is a JSON array of {"slug","name"}; indexes are 1-based positions in it.
func (q *Queries) ListNearDuplicatePairs(ctx context.Context, arg ListNearDuplicatePairsParams) ([]ListNearDuplicatePairsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNearDuplicatePairs, arg.Terms, arg.Threshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNearDuplicatePairsRow
	for rows.Next() {
		var i ListNearDuplicatePairsRow
		if err := rows.Scan(&i.LeftIndex, &i.RightIndex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostingsForClassify = `-- name: ListPostingsForClassify :many
SELECT jp.id AS posting_id,
       jp.company_id,
       c.name AS company_name,
       coalesce(s.title, '')::text AS title,
       s.description_text::text AS description_text
FROM job_postings jp
JOIN companies c ON c.id = jp.company_id
JOIN LATERAL (
    SELECT title, description_text
    FROM posting_snapshots
    WHERE job_posting_id = jp.id
    ORDER BY fetched_at DESC
    LIMIT 1
) s ON s.description_text IS NOT NULL
WHERE jp.id = ANY($1::bigint[])
ORDER BY jp.id
`

type ListPostingsForClassifyRow struct {
	PostingID       int64
	CompanyID       int64
	CompanyName     string
	Title           string
	DescriptionText string
}

// Named postings with their latest snapshot's title and description, in the
// shape selection returns. cmd/classify reads a fixed probe sample through it,
// so repeated runs and arms classify exactly the same postings.
func (q *Queries) ListPostingsForClassify(ctx context.Context, ids []int64) ([]ListPostingsForClassifyRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostingsForClassify, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostingsForClassifyRow
	for rows.Next() {
		var i ListPostingsForClassifyRow
		if err := rows.Scan(
			&i.PostingID,
			&i.CompanyID,
			&i.CompanyName,
			&i.Title,
			&i.DescriptionText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeedCorpus = `-- name: ListSeedCorpus :many
SELECT lc.job_posting_id,
       snap.description_text::text AS description_text,
       coalesce(array_agg(sk.slug ORDER BY sk.slug) FILTER (WHERE sk.slug IS NOT NULL), '{}')::text[] AS skill_slugs
FROM latest_classifications lc
JOIN LATERAL (
    SELECT description_text
    FROM posting_snapshots
    WHERE job_posting_id = lc.job_posting_id
    ORDER BY fetched_at DESC
    LIMIT 1
) snap ON snap.description_text IS NOT NULL
LEFT JOIN job_posting_skills jps ON jps.classification_id = lc.classification_id
LEFT JOIN skills sk ON sk.id = jps.skill_id
GROUP BY lc.job_posting_id, lc.classified_at, snap.description_text
ORDER BY lc.classified_at DESC, lc.job_posting_id DESC
LIMIT $1::int
`

type ListSeedCorpusRow struct {
	JobPostingID    int64
	DescriptionText string
	SkillSlugs      []string
}

// The most recently classified postings' latest descriptions, each with the
// skill slugs its latest classification assigned. The seed generator measures
// how often a skill name appears against how often it is the assigned skill.
func (q *Queries) ListSeedCorpus(ctx context.Context, maxDocs int32) ([]ListSeedCorpusRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeedCorpus, maxDocs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeedCorpusRow
	for rows.Next() {
		var i ListSeedCorpusRow
		if err := rows.Scan(&i.JobPostingID, &i.DescriptionText, pq.Array(&i.SkillSlugs)); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillLinkMass = `-- name: ListSkillLinkMass :many
SELECT s.slug, s.name, count(jps.classification_id)::bigint AS link_mass
FROM skills s
LEFT JOIN job_posting_skills jps ON jps.skill_id = s.id
GROUP BY s.id, s.slug, s.name
ORDER BY s.slug
`

type ListSkillLinkMassRow struct {
	Slug     string
	Name     string
	LinkMass int64
}

// Every live skill with its link count across all classifications. The seed
// generator chooses the noul head by it.
func (q *Queries) ListSkillLinkMass(ctx context.Context) ([]ListSkillLinkMassRow, error) {
	rows, err := q.db.QueryContext(ctx, listSkillLinkMass)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSkillLinkMassRow
	for rows.Next() {
		var i ListSkillLinkMassRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.LinkMass); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
