// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classify.sql

package db

import (
	"context"
	"encoding/json"
)

const listNearDuplicatePairs = `-- name: ListNearDuplicatePairs :many
SELECT a.ord::int AS left_index, b.ord::int AS right_index
FROM jsonb_array_elements($1::jsonb) WITH ORDINALITY AS a(term, ord)
JOIN jsonb_array_elements($1::jsonb) WITH ORDINALITY AS b(term, ord)
  ON b.ord > a.ord
WHERE greatest(
          public.similarity(a.term ->> 'slug', b.term ->> 'slug'),
          public.similarity(a.term ->> 'name', b.term ->> 'name'))::numeric
      >= $2::numeric
ORDER BY a.ord, b.ord
`

type ListNearDuplicatePairsParams struct {
	Terms     json.RawMessage
	Threshold string
}

type ListNearDuplicatePairsRow struct {
	LeftIndex  int32
	RightIndex int32
}

// Pairs among the given terms that mcp.save_enrichment's within-payload dedup
// (Phase C, 000043) would treat as one concept: the greater of slug and name
// similarity at or above its c_payload_dup_at. cmd/classify drops the less
// probable side of each pair before saving, so the save has nothing to drop.
// terms is a JSON array of {"slug","name"}; indexes are 1-based positions in it.
func (q *Queries) ListNearDuplicatePairs(ctx context.Context, arg ListNearDuplicatePairsParams) ([]ListNearDuplicatePairsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNearDuplicatePairs, arg.Terms, arg.Threshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNearDuplicatePairsRow
	for rows.Next() {
		var i ListNearDuplicatePairsRow
		if err := rows.Scan(&i.LeftIndex, &i.RightIndex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
