// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classifications.sql

package db

import (
	"context"
	"database/sql"
)

const getCurrentClassificationForPosting = `-- name: GetCurrentClassificationForPosting :one
SELECT id, job_posting_id, model, prompt_version, classified_at, seniority, notes
FROM classifications
WHERE job_posting_id = $1
ORDER BY classified_at DESC
LIMIT 1
`

func (q *Queries) GetCurrentClassificationForPosting(ctx context.Context, jobPostingID int64) (Classification, error) {
	row := q.db.QueryRowContext(ctx, getCurrentClassificationForPosting, jobPostingID)
	var i Classification
	err := row.Scan(
		&i.ID,
		&i.JobPostingID,
		&i.Model,
		&i.PromptVersion,
		&i.ClassifiedAt,
		&i.Seniority,
		&i.Notes,
	)
	return i, err
}

const getOrCreateCanonicalRole = `-- name: GetOrCreateCanonicalRole :one

INSERT INTO canonical_roles (slug, name) VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET slug = EXCLUDED.slug
RETURNING id
`

type GetOrCreateCanonicalRoleParams struct {
	Slug string
	Name string
}

// GetOrCreate pattern: ON CONFLICT DO UPDATE SET slug = EXCLUDED.slug — the no-op update
// takes a row lock and always returns the existing row, avoiding a race under READ COMMITTED.
// Only `slug` is SET (a no-op), so `created_at` and `name` on the existing row are preserved.
// created_at is the emergent-vs-seeded discriminant across canonical_roles, specializations,
// and skills — do not change this to SET name or created_at.
func (q *Queries) GetOrCreateCanonicalRole(ctx context.Context, arg GetOrCreateCanonicalRoleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateCanonicalRole, arg.Slug, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOrCreateSkill = `-- name: GetOrCreateSkill :one
INSERT INTO skills (slug, name) VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET slug = EXCLUDED.slug
RETURNING id
`

type GetOrCreateSkillParams struct {
	Slug string
	Name string
}

func (q *Queries) GetOrCreateSkill(ctx context.Context, arg GetOrCreateSkillParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateSkill, arg.Slug, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOrCreateSpecialization = `-- name: GetOrCreateSpecialization :one
INSERT INTO specializations (slug, name) VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET slug = EXCLUDED.slug
RETURNING id
`

type GetOrCreateSpecializationParams struct {
	Slug string
	Name string
}

func (q *Queries) GetOrCreateSpecialization(ctx context.Context, arg GetOrCreateSpecializationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateSpecialization, arg.Slug, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getRoleDimensionBySlug = `-- name: GetRoleDimensionBySlug :one
SELECT id, slug, name FROM role_dimensions WHERE slug = $1
`

func (q *Queries) GetRoleDimensionBySlug(ctx context.Context, slug string) (RoleDimension, error) {
	row := q.db.QueryRowContext(ctx, getRoleDimensionBySlug, slug)
	var i RoleDimension
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const insertCanonicalRoleDimension = `-- name: InsertCanonicalRoleDimension :exec
INSERT INTO canonical_role_dimensions (canonical_role_id, dimension_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertCanonicalRoleDimensionParams struct {
	CanonicalRoleID int64
	DimensionID     int64
}

// Idempotent insert — ON CONFLICT DO NOTHING; does not update existing mappings.
func (q *Queries) InsertCanonicalRoleDimension(ctx context.Context, arg InsertCanonicalRoleDimensionParams) error {
	_, err := q.db.ExecContext(ctx, insertCanonicalRoleDimension, arg.CanonicalRoleID, arg.DimensionID)
	return err
}

const insertClassification = `-- name: InsertClassification :one
INSERT INTO classifications (job_posting_id, model, prompt_version, seniority, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertClassificationParams struct {
	JobPostingID  int64
	Model         string
	PromptVersion string
	Seniority     string
	Notes         sql.NullString
}

func (q *Queries) InsertClassification(ctx context.Context, arg InsertClassificationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertClassification,
		arg.JobPostingID,
		arg.Model,
		arg.PromptVersion,
		arg.Seniority,
		arg.Notes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertJobPostingRole = `-- name: InsertJobPostingRole :exec
INSERT INTO job_posting_roles (classification_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertJobPostingRoleParams struct {
	ClassificationID int64
	RoleID           int64
}

func (q *Queries) InsertJobPostingRole(ctx context.Context, arg InsertJobPostingRoleParams) error {
	_, err := q.db.ExecContext(ctx, insertJobPostingRole, arg.ClassificationID, arg.RoleID)
	return err
}

const insertJobPostingSkill = `-- name: InsertJobPostingSkill :exec
INSERT INTO job_posting_skills (classification_id, skill_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertJobPostingSkillParams struct {
	ClassificationID int64
	SkillID          int64
}

func (q *Queries) InsertJobPostingSkill(ctx context.Context, arg InsertJobPostingSkillParams) error {
	_, err := q.db.ExecContext(ctx, insertJobPostingSkill, arg.ClassificationID, arg.SkillID)
	return err
}

const insertJobPostingSpecialization = `-- name: InsertJobPostingSpecialization :exec
INSERT INTO job_posting_specializations (classification_id, specialization_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertJobPostingSpecializationParams struct {
	ClassificationID int64
	SpecializationID int64
}

func (q *Queries) InsertJobPostingSpecialization(ctx context.Context, arg InsertJobPostingSpecializationParams) error {
	_, err := q.db.ExecContext(ctx, insertJobPostingSpecialization, arg.ClassificationID, arg.SpecializationID)
	return err
}

const listCurrentClassifications = `-- name: ListCurrentClassifications :many
SELECT DISTINCT ON (job_posting_id) id, job_posting_id, model, prompt_version, classified_at, seniority, notes
FROM classifications
ORDER BY job_posting_id, classified_at DESC
`

// Full-table DISTINCT ON — no filter or limit. Suitable for local/debug use;
// production callers should add a job_posting_id filter or pagination parameters.
func (q *Queries) ListCurrentClassifications(ctx context.Context) ([]Classification, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentClassifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Classification
	for rows.Next() {
		var i Classification
		if err := rows.Scan(
			&i.ID,
			&i.JobPostingID,
			&i.Model,
			&i.PromptVersion,
			&i.ClassifiedAt,
			&i.Seniority,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
