// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fetch_runs.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const insertFetchRun = `-- name: InsertFetchRun :one
INSERT INTO fetch_runs (company_id, started_at, status)
VALUES ($1, $2, 'in_progress')
RETURNING id
`

type InsertFetchRunParams struct {
	CompanyID int64
	StartedAt time.Time
}

func (q *Queries) InsertFetchRun(ctx context.Context, arg InsertFetchRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertFetchRun, arg.CompanyID, arg.StartedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listLatestFetchRunsByCompany = `-- name: ListLatestFetchRunsByCompany :many
SELECT DISTINCT ON (fr.company_id)
    c.name,
    fr.status,
    fr.started_at,
    fr.completed_at,
    fr.postings_count,
    fr.error_message
FROM fetch_runs fr
JOIN companies c ON c.id = fr.company_id
ORDER BY fr.company_id, fr.started_at DESC
`

type ListLatestFetchRunsByCompanyRow struct {
	Name          string
	Status        string
	StartedAt     time.Time
	CompletedAt   sql.NullTime
	PostingsCount sql.NullInt32
	ErrorMessage  sql.NullString
}

func (q *Queries) ListLatestFetchRunsByCompany(ctx context.Context) ([]ListLatestFetchRunsByCompanyRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestFetchRunsByCompany)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestFetchRunsByCompanyRow
	for rows.Next() {
		var i ListLatestFetchRunsByCompanyRow
		if err := rows.Scan(
			&i.Name,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PostingsCount,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFetchRunFailed = `-- name: MarkFetchRunFailed :exec
UPDATE fetch_runs
SET status = 'failed', completed_at = $2, error_message = $3
WHERE id = $1
`

type MarkFetchRunFailedParams struct {
	ID           int64
	CompletedAt  sql.NullTime
	ErrorMessage sql.NullString
}

func (q *Queries) MarkFetchRunFailed(ctx context.Context, arg MarkFetchRunFailedParams) error {
	_, err := q.db.ExecContext(ctx, markFetchRunFailed, arg.ID, arg.CompletedAt, arg.ErrorMessage)
	return err
}

const markFetchRunSuccess = `-- name: MarkFetchRunSuccess :exec
UPDATE fetch_runs
SET status = 'success', completed_at = $2, postings_count = $3
WHERE id = $1
`

type MarkFetchRunSuccessParams struct {
	ID            int64
	CompletedAt   sql.NullTime
	PostingsCount sql.NullInt32
}

func (q *Queries) MarkFetchRunSuccess(ctx context.Context, arg MarkFetchRunSuccessParams) error {
	_, err := q.db.ExecContext(ctx, markFetchRunSuccess, arg.ID, arg.CompletedAt, arg.PostingsCount)
	return err
}
