// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fetcher.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const insertPostingSnapshot = `-- name: InsertPostingSnapshot :exec
INSERT INTO posting_snapshots (
    job_posting_id,
    fetched_at,
    title,
    location_text,
    department,
    team,
    employment_type,
    workplace_type,
    posted_at,
    job_url,
    raw_data,
    source_first_published_at,
    source_last_modified_at,
    location_texts,
    fetch_run_id,
    description_text,
    compensation_min,
    compensation_max,
    compensation_currency,
    compensation_period
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
`

type InsertPostingSnapshotParams struct {
	JobPostingID           int64
	FetchedAt              time.Time
	Title                  sql.NullString
	LocationText           sql.NullString
	Department             sql.NullString
	Team                   sql.NullString
	EmploymentType         sql.NullString
	WorkplaceType          sql.NullString
	PostedAt               sql.NullTime
	JobUrl                 sql.NullString
	RawData                json.RawMessage
	SourceFirstPublishedAt sql.NullTime
	SourceLastModifiedAt   sql.NullTime
	LocationTexts          []string
	FetchRunID             sql.NullInt64
	DescriptionText        sql.NullString
	CompensationMin        sql.NullInt64
	CompensationMax        sql.NullInt64
	CompensationCurrency   sql.NullString
	CompensationPeriod     sql.NullString
}

func (q *Queries) InsertPostingSnapshot(ctx context.Context, arg InsertPostingSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertPostingSnapshot,
		arg.JobPostingID,
		arg.FetchedAt,
		arg.Title,
		arg.LocationText,
		arg.Department,
		arg.Team,
		arg.EmploymentType,
		arg.WorkplaceType,
		arg.PostedAt,
		arg.JobUrl,
		arg.RawData,
		arg.SourceFirstPublishedAt,
		arg.SourceLastModifiedAt,
		pq.Array(arg.LocationTexts),
		arg.FetchRunID,
		arg.DescriptionText,
		arg.CompensationMin,
		arg.CompensationMax,
		arg.CompensationCurrency,
		arg.CompensationPeriod,
	)
	return err
}

const listCompaniesWithATS = `-- name: ListCompaniesWithATS :many
SELECT id, name, ats, board_token, created_at, employee_count_range, founded_year, funding_stage, total_funding_usd, industry, company_type, careers_page_url, enriched_at
FROM companies
WHERE ats IS NOT NULL
ORDER BY name
`

func (q *Queries) ListCompaniesWithATS(ctx context.Context) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, listCompaniesWithATS)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ats,
			&i.BoardToken,
			&i.CreatedAt,
			&i.EmployeeCountRange,
			&i.FoundedYear,
			&i.FundingStage,
			&i.TotalFundingUsd,
			&i.Industry,
			&i.CompanyType,
			&i.CareersPageUrl,
			&i.EnrichedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestDescriptionsByCompany = `-- name: ListLatestDescriptionsByCompany :many
SELECT job_posting_id, description_text
FROM (
    SELECT DISTINCT ON (ps.job_posting_id)
        ps.job_posting_id,
        ps.description_text::text AS description_text
    FROM posting_snapshots ps
    JOIN job_postings jp ON jp.id = ps.job_posting_id
    WHERE jp.company_id = $1
    ORDER BY ps.job_posting_id, ps.fetched_at DESC
) latest
WHERE description_text IS NOT NULL
`

type ListLatestDescriptionsByCompanyRow struct {
	JobPostingID    int64
	DescriptionText string
}

// Latest snapshot's description_text per job_posting for a company.
// Skips postings whose latest snapshot has NULL description_text.
// ::text cast is intentional: forces sqlc to emit a plain string instead of
// sql.NullString. The outer WHERE guarantees non-null at the DB level; the
// cast surfaces that guarantee in the generated Go type.
func (q *Queries) ListLatestDescriptionsByCompany(ctx context.Context, companyID int64) ([]ListLatestDescriptionsByCompanyRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestDescriptionsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestDescriptionsByCompanyRow
	for rows.Next() {
		var i ListLatestDescriptionsByCompanyRow
		if err := rows.Scan(&i.JobPostingID, &i.DescriptionText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJobPosting = `-- name: UpsertJobPosting :one
INSERT INTO job_postings (company_id, source_type, source_url, source_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (company_id, source_url) DO UPDATE SET source_id = EXCLUDED.source_id
RETURNING id
`

type UpsertJobPostingParams struct {
	CompanyID  int64
	SourceType string
	SourceUrl  string
	SourceID   sql.NullString
}

// DO UPDATE (not DO NOTHING) so RETURNING id fires on conflict — the caller
// needs the row id to write the snapshot. SET source_id is usually a no-op by
// value but self-heals if an ATS reassigns the id for an existing source_url.
// Append-only semantics apply to posting_snapshots, not this table.
func (q *Queries) UpsertJobPosting(ctx context.Context, arg UpsertJobPostingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertJobPosting,
		arg.CompanyID,
		arg.SourceType,
		arg.SourceUrl,
		arg.SourceID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
