// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type CanonicalRole struct {
	ID        int64
	Slug      string
	Name      string
	CreatedAt time.Time
}

type CanonicalRoleDimension struct {
	CanonicalRoleID int64
	DimensionID     int64
}

type Classification struct {
	ID            int64
	JobPostingID  int64
	Model         string
	PromptVersion string
	ClassifiedAt  time.Time
	Seniority     string
	Notes         sql.NullString
}

type Company struct {
	ID                 int64
	Name               string
	Ats                string
	BoardToken         string
	CreatedAt          time.Time
	EmployeeCountRange sql.NullString
	FoundedYear        sql.NullInt32
	FundingStage       sql.NullString
	TotalFundingUsd    sql.NullInt64
	Industry           sql.NullString
	CompanyType        sql.NullString
	CareersPageUrl     sql.NullString
	EnrichedAt         sql.NullTime
}

type FetchRun struct {
	ID            int64
	CompanyID     int64
	StartedAt     time.Time
	CompletedAt   sql.NullTime
	Status        string
	ErrorMessage  sql.NullString
	PostingsCount sql.NullInt32
}

type JobPosting struct {
	ID          int64
	CompanyID   int64
	SourceType  string
	SourceUrl   string
	SourceID    sql.NullString
	Cities      []string
	FirstSeenAt time.Time
}

type JobPostingRole struct {
	ClassificationID int64
	RoleID           int64
}

type JobPostingSkill struct {
	ClassificationID int64
	SkillID          int64
}

type JobPostingSpecialization struct {
	ClassificationID int64
	SpecializationID int64
}

type LatestSuccessfulFetchRun struct {
	FetchRunID int64
	CompanyID  int64
	StartedAt  time.Time
}

type OpenPosting struct {
	JobPostingID int64
	FetchRunID   int64
}

type OpenPostingTaxonomy struct {
	JobPostingID int64
	TermKind     string
	Slug         string
	Name         string
}

type OpenPostingsDisplay struct {
	JobPostingID          int64
	CompanyID             int64
	CompanyName           string
	RunStartedAt          time.Time
	Title                 sql.NullString
	LocationText          sql.NullString
	WorkplaceType         sql.NullString
	CompensationMin       sql.NullInt64
	CompensationMax       sql.NullInt64
	CompensationCurrency  sql.NullString
	ClassificationID      sql.NullInt64
	Seniority             sql.NullString
	WorkplaceTypeResolved sql.NullString
	WorkplaceTypeSource   sql.NullString
}

type PostingSnapshot struct {
	ID                     int64
	JobPostingID           int64
	FetchedAt              time.Time
	Title                  sql.NullString
	LocationText           sql.NullString
	Department             sql.NullString
	Team                   sql.NullString
	EmploymentType         sql.NullString
	WorkplaceType          sql.NullString
	PostedAt               sql.NullTime
	JobUrl                 sql.NullString
	RawData                json.RawMessage
	SourceFirstPublishedAt sql.NullTime
	SourceLastModifiedAt   sql.NullTime
	LocationTexts          []string
	FetchRunID             sql.NullInt64
	DescriptionText        sql.NullString
	CompensationMin        sql.NullInt64
	CompensationMax        sql.NullInt64
	CompensationCurrency   sql.NullString
	CompensationPeriod     sql.NullString
}

type RoleDimension struct {
	ID   int64
	Slug string
	Name string
}

type Skill struct {
	ID        int64
	Slug      string
	Name      string
	CreatedAt time.Time
}

type Specialization struct {
	ID        int64
	Slug      string
	Name      string
	CreatedAt time.Time
}

type UnsupportedCompany struct {
	ID               int64
	Name             string
	Url              sql.NullString
	DetectedPlatform sql.NullString
	Reason           string
	FirstSeenAt      time.Time
	LastCheckedAt    time.Time
}
