// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrich.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const listCanonicalRoles = `-- name: ListCanonicalRoles :many
SELECT id, slug, name FROM canonical_roles ORDER BY slug
`

type ListCanonicalRolesRow struct {
	ID   int64
	Slug string
	Name string
}

func (q *Queries) ListCanonicalRoles(ctx context.Context) ([]ListCanonicalRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCanonicalRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCanonicalRolesRow
	for rows.Next() {
		var i ListCanonicalRolesRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassifiedAmong = `-- name: ListClassifiedAmong :many
SELECT job_posting_id AS posting_id
FROM classifications
WHERE job_posting_id = ANY($1::bigint[])
GROUP BY job_posting_id
`

// Returns the subset of @ids that already have at least one classifications row.
// Used under --force to flag postings that will produce duplicate-write surprises
// in re-enrichment. The ::bigint[] cast is required for sqlc to emit a pq.Array
// parameter so a Go []int64 marshals correctly through database/sql.
func (q *Queries) ListClassifiedAmong(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listClassifiedAmong, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var posting_id int64
		if err := rows.Scan(&posting_id); err != nil {
			return nil, err
		}
		items = append(items, posting_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleDimensions = `-- name: ListRoleDimensions :many
SELECT id, slug, name FROM role_dimensions ORDER BY slug
`

func (q *Queries) ListRoleDimensions(ctx context.Context) ([]RoleDimension, error) {
	rows, err := q.db.QueryContext(ctx, listRoleDimensions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleDimension
	for rows.Next() {
		var i RoleDimension
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkills = `-- name: ListSkills :many
SELECT id, slug, name FROM skills ORDER BY slug
`

type ListSkillsRow struct {
	ID   int64
	Slug string
	Name string
}

func (q *Queries) ListSkills(ctx context.Context) ([]ListSkillsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSkillsRow
	for rows.Next() {
		var i ListSkillsRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecializations = `-- name: ListSpecializations :many
SELECT id, slug, name FROM specializations ORDER BY slug
`

type ListSpecializationsRow struct {
	ID   int64
	Slug string
	Name string
}

func (q *Queries) ListSpecializations(ctx context.Context) ([]ListSpecializationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSpecializations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpecializationsRow
	for rows.Next() {
		var i ListSpecializationsRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnclassifiedPostings = `-- name: ListUnclassifiedPostings :many

SELECT jp.id AS posting_id,
       jp.company_id,
       s.title,
       s.description_text
FROM job_postings jp
JOIN LATERAL (
    SELECT title, description_text
    FROM posting_snapshots
    WHERE job_posting_id = jp.id
    ORDER BY fetched_at DESC
    LIMIT 1
) s ON true
WHERE s.description_text IS NOT NULL
  AND ($1::text = '' OR (s.title ILIKE '%' || $1::text || '%' OR s.description_text ILIKE '%' || $1::text || '%'))
  AND NOT EXISTS (
      SELECT 1 FROM classifications WHERE job_posting_id = jp.id
  )
ORDER BY jp.first_seen_at ASC
LIMIT $2::int
`

type ListUnclassifiedPostingsParams struct {
	Focus    string
	RowLimit int32
}

type ListUnclassifiedPostingsRow struct {
	PostingID       int64
	CompanyID       int64
	Title           sql.NullString
	DescriptionText sql.NullString
}

// Queries that drive the batch-enrich Go command. Selection uses a LATERAL join
// to the latest posting_snapshots row per job_posting, an optional ILIKE focus
// prefilter, and oldest-first ordering to process the backlog in stable priority.
// The Forced variant drops the NOT EXISTS classifications guard so already-
// classified postings are eligible for re-enrichment under --force.
//
// @row_limit is named (not `limit`) because `limit` is a reserved word in
// sqlc's named-parameter syntax. Column aliases (`posting_id`, `description_text`)
// pin the generated struct field names (PostingID, DescriptionText).
func (q *Queries) ListUnclassifiedPostings(ctx context.Context, arg ListUnclassifiedPostingsParams) ([]ListUnclassifiedPostingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnclassifiedPostings, arg.Focus, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnclassifiedPostingsRow
	for rows.Next() {
		var i ListUnclassifiedPostingsRow
		if err := rows.Scan(
			&i.PostingID,
			&i.CompanyID,
			&i.Title,
			&i.DescriptionText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnclassifiedPostingsForced = `-- name: ListUnclassifiedPostingsForced :many
SELECT jp.id AS posting_id,
       jp.company_id,
       s.title,
       s.description_text
FROM job_postings jp
JOIN LATERAL (
    SELECT title, description_text
    FROM posting_snapshots
    WHERE job_posting_id = jp.id
    ORDER BY fetched_at DESC
    LIMIT 1
) s ON true
WHERE s.description_text IS NOT NULL
  AND ($1::text = '' OR (s.title ILIKE '%' || $1::text || '%' OR s.description_text ILIKE '%' || $1::text || '%'))
ORDER BY jp.first_seen_at ASC
LIMIT $2::int
`

type ListUnclassifiedPostingsForcedParams struct {
	Focus    string
	RowLimit int32
}

type ListUnclassifiedPostingsForcedRow struct {
	PostingID       int64
	CompanyID       int64
	Title           sql.NullString
	DescriptionText sql.NullString
}

func (q *Queries) ListUnclassifiedPostingsForced(ctx context.Context, arg ListUnclassifiedPostingsForcedParams) ([]ListUnclassifiedPostingsForcedRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnclassifiedPostingsForced, arg.Focus, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnclassifiedPostingsForcedRow
	for rows.Next() {
		var i ListUnclassifiedPostingsForcedRow
		if err := rows.Scan(
			&i.PostingID,
			&i.CompanyID,
			&i.Title,
			&i.DescriptionText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
