// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fetch_runs.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const insertFetchRun = `-- name: InsertFetchRun :one
INSERT INTO fetch_runs (company_id, started_at, status)
VALUES ($1, $2, 'in_progress')
RETURNING id
`

type InsertFetchRunParams struct {
	CompanyID int64
	StartedAt time.Time
}

// $1: company_id, $2: started_at
func (q *Queries) InsertFetchRun(ctx context.Context, arg InsertFetchRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertFetchRun, arg.CompanyID, arg.StartedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markFetchRunFailed = `-- name: MarkFetchRunFailed :exec
UPDATE fetch_runs
SET status = 'failed', completed_at = $2, error_message = $3
WHERE id = $1
`

type MarkFetchRunFailedParams struct {
	ID           int64
	CompletedAt  sql.NullTime
	ErrorMessage sql.NullString
}

// $1: id, $2: completed_at, $3: error_message
func (q *Queries) MarkFetchRunFailed(ctx context.Context, arg MarkFetchRunFailedParams) error {
	_, err := q.db.ExecContext(ctx, markFetchRunFailed, arg.ID, arg.CompletedAt, arg.ErrorMessage)
	return err
}

const markFetchRunSuccess = `-- name: MarkFetchRunSuccess :exec
UPDATE fetch_runs
SET status = 'success', completed_at = $2, postings_count = $3
WHERE id = $1
`

type MarkFetchRunSuccessParams struct {
	ID            int64
	CompletedAt   sql.NullTime
	PostingsCount sql.NullInt32
}

// $1: id, $2: completed_at, $3: postings_count
func (q *Queries) MarkFetchRunSuccess(ctx context.Context, arg MarkFetchRunSuccessParams) error {
	_, err := q.db.ExecContext(ctx, markFetchRunSuccess, arg.ID, arg.CompletedAt, arg.PostingsCount)
	return err
}
