// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fetcher.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const insertPostingSnapshot = `-- name: InsertPostingSnapshot :exec
INSERT INTO posting_snapshots (
    job_posting_id,
    fetched_at,
    title,
    location_text,
    department,
    team,
    employment_type,
    workplace_type,
    posted_at,
    job_url,
    raw_data
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertPostingSnapshotParams struct {
	JobPostingID   int64
	FetchedAt      time.Time
	Title          sql.NullString
	LocationText   sql.NullString
	Department     sql.NullString
	Team           sql.NullString
	EmploymentType sql.NullString
	WorkplaceType  sql.NullString
	PostedAt       sql.NullTime
	JobUrl         sql.NullString
	RawData        json.RawMessage
}

func (q *Queries) InsertPostingSnapshot(ctx context.Context, arg InsertPostingSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertPostingSnapshot,
		arg.JobPostingID,
		arg.FetchedAt,
		arg.Title,
		arg.LocationText,
		arg.Department,
		arg.Team,
		arg.EmploymentType,
		arg.WorkplaceType,
		arg.PostedAt,
		arg.JobUrl,
		arg.RawData,
	)
	return err
}

const listCompaniesWithATS = `-- name: ListCompaniesWithATS :many
SELECT id, name, ats, board_token, created_at, employee_count_range, founded_year, funding_stage, total_funding_usd, industry, company_type, careers_page_url, enriched_at
FROM companies
WHERE ats IS NOT NULL
ORDER BY name
`

func (q *Queries) ListCompaniesWithATS(ctx context.Context) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, listCompaniesWithATS)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ats,
			&i.BoardToken,
			&i.CreatedAt,
			&i.EmployeeCountRange,
			&i.FoundedYear,
			&i.FundingStage,
			&i.TotalFundingUsd,
			&i.Industry,
			&i.CompanyType,
			&i.CareersPageUrl,
			&i.EnrichedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJobPosting = `-- name: UpsertJobPosting :one
INSERT INTO job_postings (company_id, source_type, source_url, source_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (company_id, source_url) DO UPDATE SET source_id = EXCLUDED.source_id
RETURNING id
`

type UpsertJobPostingParams struct {
	CompanyID  int64
	SourceType string
	SourceUrl  string
	SourceID   sql.NullString
}

func (q *Queries) UpsertJobPosting(ctx context.Context, arg UpsertJobPostingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertJobPosting,
		arg.CompanyID,
		arg.SourceType,
		arg.SourceUrl,
		arg.SourceID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
