// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type CanonicalRole struct {
	ID       int64
	Slug     string
	Name     string
	Category string
}

type Company struct {
	ID                 int64
	Name               string
	Ats                string
	BoardToken         string
	CreatedAt          time.Time
	EmployeeCountRange sql.NullString
	FoundedYear        sql.NullInt32
	FundingStage       sql.NullString
	TotalFundingUsd    sql.NullInt64
	Industry           sql.NullString
	CompanyType        sql.NullString
	CareersPageUrl     sql.NullString
	EnrichedAt         sql.NullTime
}

type JobPosting struct {
	ID          int64
	CompanyID   int64
	SourceType  string
	SourceUrl   string
	SourceID    sql.NullString
	Cities      []string
	FirstSeenAt time.Time
}

type JobPostingRole struct {
	JobPostingID int64
	RoleID       int64
}

type JobPostingSkill struct {
	JobPostingID int64
	SkillID      int64
}

type JobPostingSpecialization struct {
	JobPostingID     int64
	SpecializationID int64
}

type PostingSnapshot struct {
	ID             int64
	JobPostingID   int64
	FetchedAt      time.Time
	Title          sql.NullString
	LocationText   sql.NullString
	Department     sql.NullString
	Team           sql.NullString
	EmploymentType sql.NullString
	WorkplaceType  sql.NullString
	PostedAt       sql.NullTime
	JobUrl         sql.NullString
	RawData        json.RawMessage
}

type Skill struct {
	ID   int64
	Slug string
	Name string
}

type Specialization struct {
	ID   int64
	Slug string
	Name string
}
