// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: onboard.sql

package db

import (
	"context"
)

const findCompanyDedupStatus = `-- name: FindCompanyDedupStatus :one
SELECT
    c.id AS company_id,
    EXISTS (
        SELECT 1
        FROM job_postings jp
        JOIN posting_snapshots ps ON ps.job_posting_id = jp.id
        WHERE jp.company_id = c.id
          AND ps.fetched_at >= now() - make_interval(days => $1::int)
    ) AS has_recent_snapshot
FROM companies c
WHERE c.ats = $2
  AND c.board_token = $3
`

type FindCompanyDedupStatusParams struct {
	RecencyDays int32
	Ats         string
	BoardToken  string
}

type FindCompanyDedupStatusRow struct {
	CompanyID         int64
	HasRecentSnapshot bool
}

// Used by cmd/onboard to dedup a sidecar record against the companies table.
// Returns the company id if a row with the given (ats, board_token) exists,
// plus a boolean indicating whether any of that company's postings have a
// posting_snapshots row with fetched_at within the recency window.
//
// Recency window: snapshots from now() - (recency_days days) and later count
// as "recent". The caller passes the watchlist's 30-day threshold as an
// integer; pushing the interval construction into SQL avoids a clock-skew
// gap between app server and database, and avoids the awkward
// interval-as-int64 type sqlc emits for raw interval parameters.
//
// Returns zero rows if no company matches. Returns exactly one row if a
// company exists, with has_recent_snapshot=false when the company has no
// postings or no snapshots in the window.
func (q *Queries) FindCompanyDedupStatus(ctx context.Context, arg FindCompanyDedupStatusParams) (FindCompanyDedupStatusRow, error) {
	row := q.db.QueryRowContext(ctx, findCompanyDedupStatus, arg.RecencyDays, arg.Ats, arg.BoardToken)
	var i FindCompanyDedupStatusRow
	err := row.Scan(&i.CompanyID, &i.HasRecentSnapshot)
	return i, err
}
